import type { NextPage } from "next";
import Head from "next/head";
import ReactMarkdown from "react-markdown";
import React from "react";
import Prism, { languages } from "prismjs";
import { JSCode } from "@components";

const Home: NextPage = () => {
  const [loaded, setLoaded] = React.useState(false);

  const markdown = `
# hello
##### world



~~~~tsx
React.useEffect(()=>{
  Prism.highlightAll()
},[])

return (
  <div>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <div className="">
      <JSCode>
      
      </JSCode>
      <ReactMarkdown>{markdown}</ReactMarkdown>
    </div>
  </div>
  );
};
~~~~

## python

~~~~cs

class main {
  private String noob(){
    String name = "peter"

    return name
  }
}

~~~~


`;

  React.useEffect(() => {
    Prism.highlightAll();
  }, []);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="">
        <ReactMarkdown
          components={{
            code({ children, node, className }) {
              return <code className={`${className}`}>{children}</code>;
            },
          }}
        >
          {markdown}
        </ReactMarkdown>
      </div>
    </div>
  );
};

export default Home;
